defaults:
  - default
  - _self_

_target_: helpers.models.modules.temporal.Modular1DCNN
num_classes: 1
use_batchnorm: true
in_channels: 19
conv_layers:
  - out_channels: 32
    kernel_size: 7
    stride: 1
    padding: 3
    pool: true
  - out_channels: 64
    kernel_size: 5
    stride: 1
    padding: 2
    pool: true
  - out_channels: 128
    kernel_size: 3
    stride: 1
    padding: 1
    pool: false