module:
  _target_: helpers.models.gcn_lstm_att.GCN_LSTM_ATT
  gcn_in_features: 64
  gcn_out_features: 32
  output_size: 1
  window_size: 125
  step_size: 62
  lstm_input_size: 128
  lstm_hidden_size: 128
  lstm_layers: 3
  bidirectional: False
  attention_dim: 64
  dropout: 0.5
signal_transform: time_filtering
distance_file: "data/distances_3d.csv"
distance_thresh: 1
normalize: False